### ISSUE TITLE
Accuracy of Inference with Instahide

### ISSUE THREAD

**Issue by MADONOKOUKI** [Hazelsuko07/InstaHide#1]
@Hazelsuko07 
I want to know how to evaluate the accuracy of inference with Instahide and The definition of InstaHide during inference.
(Table2 on the paper https://arxiv.org/pdf/2010.02772.pdf)
In my experiment using this GitHub code, the classification loss in training is very high although the classification loss during the inference is very low if we use the real images.

Therefore, I'm wondering about the evaluation of inference with Instahide.

**Comment by Hazelsuko07** [comment]
Hi, you may refer to Section 3.3 in our paper (https://arxiv.org/pdf/2010.02772.pdf) for a detailed description of inference with InstaHide.

Here is a more detailed explanation for using InstaHide during inference. Let's denote the trained model as f(). As we described in the paper, when using InstaHide during inference on some private example x, we generate K encryptions of x using different public samples and coefficients, resulting in \tilde{x}_1, ..., \tilde{x}_K. We then average the predictions of f(\tilde{x}_1), ... f(\tilde{x}_K), and use it as the final prediction of x.

In our experiment, setting K to 10~20 can give reasonable accuracy.
