### ISSUE TITLE
How to do inference using an instahide test set?

### ISSUE THREAD

**Issue by gursimar** [Hazelsuko07/InstaHide#5]
Hi,
It seems like neither the code nor the paper provides implementation details for inference using the instahide test data (the 'in inference' setting in Table2). When we mix a couple of images from the private test set (let's say 1,5 for MNIST), we will get a corresponding soft target (say something like 0,0.3,0,0,0,0.7, 0,0,0,0). However, accuracy computation requires a hard label (like 1 or 5). What exactly is the procedure to compute the classification accuracy using the soft targets provided by the instahide mixing technique?

**Comment by Hazelsuko07** [comment]
Hi @gursimar, 

Many thanks for your question! 
 
Here is the pseudo-code for running inference on an original input `x` with InstaHide:
```python
for t in T:
    x_hat^t = InstaHide(x, x_1^t, x_2^t, ... x_{k-1}^t)   # Generate InstaHide images by combining x with (k-1) other randomly chosen images (using random coefficients that sum to 1)
    y_hat^t = f(x_hat^t)                                  # Run inference on x_hat^t, f() is the model trained with InstaHide
y_hat = argmax \sum_{t=1}^T y_hat^t                           # Using the averaged prediction as final prediction
```
Typically, we require T > 15 to get good inference accuracy. To improve the accuracy, you may constrain the coefficient for `x` (say assert it to be larger than 0.5).
